### ISSUE TITLE
Check for specific error codes when authenticating users

### ISSUE THREAD

**Issue by bshmueli** [ISS-Security/credence-app#1]
Here's a possible solution

        routing.post do
          account = AuthenticateAccount.new(App.config).call(
            username: routing.params['username'],
            password: routing.params['password'])
          session[:current_account] = account

          flash[:notice] = "Welcome back #{account['username']}!"
          routing.redirect '/'
        rescue AuthenticateAccount::UnauthorizedError
          flash[:error] = 'Username and password did not match our records'
          routing.redirect @login_route
        rescue StandardError
          flash[:error] = 'Internal error, please try again later'
          routing.redirect @login_route
        end

**Comment by soumyaray** [comment]
thanks!!!  sadly, the `AuthenticateAccount` service object returns `UnauthorizedError` for any non-200 HTTP code.  I suspect I'll have to fix the service first before your fix works — will try it out soon.

**Comment by soumyaray** [comment]
Fixed (I think)
